### ISSUE TITLE
ntest_nexus_structure is failing

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1790]
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=ntest_nexus_structure&date=2019-08-13 . Must be a side effect of #1788 since no other PRs were merged.

<img width="825" alt="Screen Shot 2019-08-13 at 9 59 37 AM" src="https://user-images.githubusercontent.com/13683814/62947776-1cb51000-bdb1-11e9-95a8-5e72446d6e31.png">

**Comment by jtkrogel** [comment]
The failure is related to the code added in #1728.  The unit tests accompanying #1728 were enabled in #1765.

Oddly, the failure is related to the use of a standard flag in NumPy, the "axis" keyword argument to the "norm" function:
```
Test output

Test name     : structure
Test sublabel : test_count_kshells
Test exception: "TypeError: norm() got an unexpected keyword argument 'axis'"
Test backtrace:
  File "/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/bin/nxs-test", line 504, in run
    self.operation()
  File "/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/bin/nxs-test", line 2716, in structure
    nunit_all()
  File "/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/bin/nxs-test", line 391, in nunit_all
    run_external_unit_test(test_name,unit_test)
  File "/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/bin/nxs-test", line 417, in run_external_unit_test
    unit_test()
  File "/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/tests/unit/test_structure.py", line 7, in test_count_kshells
    nksh = s1.count_kshells(kcut)
  File "/data/ci/scratch/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack/nexus/lib/structure.py", line 1242, in count_kshells
    kmags = np.linalg.norm(kvecs, axis=-1)

Test status: fail
```

This is strange because the "axis" keyword was added to NumPy back in version 1.8.0 (in 2013).  Additionally all tests pass on my workstation (NumPy version 1.11.3) and on my laptop (NumPy version 1.15.4).

**Comment by jtkrogel** [comment]
The test is failing on hyperion and oxygen.  Logging into oxygen I find the NumPy version is 1.7.1 (from about April 2013).

The version there (and presumbably on hyperion) is simply too old.

**Comment by jtkrogel** [comment]
@prckent How hard is is to use a newer version of NumPy on the testing machines?

**Comment by prckent** [comment]
Updating numpy is trivial e.g. "spack install py-numpy" works https://spack.readthedocs.io/en/latest/package_list.html#py-numpy . I think the news is that we have a minimum numpy version and should check & abort appropriately. With knowledge of the minimum version we can test vs that instead of the random system versions.

**Comment by jtkrogel** [comment]
Fair enough.  NumPy is a hard dependency.  We should probably test with the oldest supported and the newest accessible versions.  Given our 2 year rule for QMCPACK, I don't feel too bad about breaking builds from 6 years ago.

Perhaps I should add an explicit test in the testing system for the NumPy version?  Running with older versions may still work, except at the edges, so perhaps a warning from the main Nexus is most appropriate.

**Comment by prckent** [comment]
Implementing the 2 year rule would be consistent. It would also be helpful to state the requirements. e.g. there is also use of pandas and h5py as well as numpy. Which versions are needed? I like the idea of printing a warning from NEXUS main() if too old a version of these dependencies is imported.

**Comment by jtkrogel** [comment]
I will add a warning + test for the now known NumPy 1.8.0 dependency.  Once the test system is rounded out, it would be a good exercise to use Spack to determine the limits of the other package versions.  Independently, the optional features enabled by libraries apart from NumPy should be delineated in the manual.

**Comment by prckent** [comment]
From tonight the nightlies will attempt to use a spack installed python, h5py, pandas, and numpy. The overnight structure tests should now pass.

**Comment by prckent** [comment]
Sadly the apparently successfully installed packages fail on import due to missing dependencies. I'll have to check whether a newer spack fixes this. Installing these packages also broke the existing test scripts due to creating ambiguities for package references where previously there were none....

**Comment by prckent** [comment]
After the python ugrade, this is working on oxygen now. e.g.
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=ntest_nexus_structure&date=2019-08-16

**Comment by prckent** [comment]
Working here https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=ntest_nexus_structure&date=2021-03-23
