### PR TITLE
Add initial hip cmake

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Initial HIP CMake updates. Discussion: I'm currently using ENABLE_HIP and added a HIP_PATH and ROCM_PATH. In retrospect HIP_PATH is probably redundant as it's usually ${ROCM_PATH}/hip. I think HIP_PATH was just included in the HIP cmake example, which I copied.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

AMD MI50

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
What is the cmake command line you use to build HIP using CUDA underlying?

**Comment by fdmalone** [comment]
I gave up trying to get AFQMC to compile with HIP on nvidea for the moment. Some hip marshalling libraries don't exist (no hipSolver for example). Otherwise, in the small examples I tried 
hipcc should just work.

When using mpicxx to compile the non hip (AFQMC) source on AMD I had to add -D__HIP_PLATFORM_HCC__ . I also am currently linking to the rocm libaries manually through DQMC_EXTRA_LIBS.

**Comment by fdmalone** [comment]
Another thing that tripped me up was that -Drestrict=__restrict__ which we add to our defines was causing compilation errors with v3.3.0 of rocm, v3.5.0 seems to be fine.

**Comment by ye-luo** [comment]
There are incompatible changes between 3.3 and 3.5 due to the deprecation of HCC. So let us ignore rocm 3.3. Could you provide your build recipe with rocm 3.5 used?

**Comment by fdmalone** [comment]
cmake -DCMAKE_C_COMPILER=$(which mpicc) -DCMAKE_CXX_COMPILER=$(which mpicxx) \
-DHIP_PATH=${HIP_HOME} -DROCM_PATH=${ROCM_HOME} \
-DBUILD_AFQMC=1 -DENABLE_HIP=1 \
-DQMC_COMPLEX=1 \
-DENABLE_TIMERS=1 \
-DQMC_NO_SLOW_CUSTOM_TESTING_COMMANDS=1 \
-DCMAKE_CXX_FLAGS="-D__HIP_PLATFORM_HCC__ -DENABLE_HIP=1" \
-DBOOST_ROOT=${BOOST_ROOT} \
-DQMC_INCLUDE=";/opt/rocm-3.5.0/include;/opt/rocm-3.5.0/hip/include/hip" \
-DMPIEXEC_NUMPROC_FLAG='-n' \
-DMPIEXEC='srun' \
-DQMC_EXTRA_LIBS="-L${BOOST_ROOT}/stage/lib -lboost_serialization -Wl,-rpath=${BOOST_ROOT}/stage/lib -I${ROCM_HOME}/include -L${ROCM_HOME}/lib -Wl,-rpath=${ROCM_HOME} -lrocsolver -lrocrand -lhipsparse -lhipblas -lhip_hcc -L/usr/lib64/atlas/ -lsatlas -Wl,-rpath=/usr/lib64/atlas/"

**Comment by fdmalone** [comment]
The link flags is pretty much just copy paste from a cuda build script. Not sure if everything is necessary.

**Comment by prckent** [comment]
@ye-luo Are updates needed or can we merge?

**Comment by ye-luo** [comment]
@prckent waiting for a build recipe from @fdmalone working with rocm 3.5

**Comment by fdmalone** [comment]
Oh sorry. The issue with rocm 3.5 aren't related to the cmake recipe, I'm working on fixing the remainging test failures in afqmc.

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
ROCM still has too many problems. @fdmalone you are luck if you get anything up and running. I fixed some source code problem missing a few "ifndef". I added cmake entry ENABLE_HIP and ENABLE_ROCM and rearranged the include path and compile definitions. So the simplified cmake line becomes.
```
cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DQMC_COMPLEX=1 -DQMC_NO_SLOW_CUSTOM_TESTING_COMMANDS=1  -DBUILD_AFQMC=1 -DENABLE_HIP=ON -DENABLE_ROCM=ON  -DROCM_ROOT=$ROCM_HOME ..
```
I'm using rocm 3.5.

Unlike CUDA giving a warning. HIP clang emits an error
```
opt/qmcpack/src/AFQMC/Numerics/detail/HIP/Kernels/determinant.hip.cpp:65:34: error: initialization is not supported for __shared__ variables.
   __shared__ thrust::complex<T> tmp[256];
                                 ^~~
```
This is source level issue and needs to be addressed.
For the CUDA warning, it can removed using uninitialized_array
see `Platforms/CUDA/cuBLAS_missing_functions.cu`. But not sure if this works for AMD.

On my local machine with AOMP used as hip-clang, I can set `HCC_OPTIONS "-Wno-cuda-shared-init"` to bypass the error but I'm taking advantage of an error handling bug in my AOMP clang. Then I'm able to finish 'make -j32 afqmc' all the compilation but failed at linking of missing kernels. It is less clear whether it is due to compiler bugs or source codes.

**Comment by ye-luo** [comment]
I think we should merge this PR and solve build problems later as long as the CI pass.

**Comment by fdmalone** [comment]
Yes, as I said the issues are with the AFQMC source that I'm currently fixing. This PR was intended just to include the HIP CMake. rocm 3.5 broke the original PR. I've fixed most of the remaining issues.

**Comment by PDoakORNL** [comment]
I don't think __shared__ is such a thing for AMD.  I've heard them mention that lack of interest in it several times. I didn't find our use of it for the splines accomplished much at least for my CUDA spline evaluation and dropped it.

**Comment by fdmalone** [comment]
Yes, I have a fix for this. The problem is with `__shared__` for complex (or a struct in general I think). This only started to cause issues  with rocm3.5

**Comment by ye-luo** [comment]
I also noticed that HIP(kernels) and ROCM(libraries) are blended in header files. It becomes hard to have simple dependency. AFQMC needs to treat header inclusion more seriously.

**Comment by fdmalone** [comment]
@ye-luo initially this PR was meant to touch only the CMake source. I will fix the remaining compilation errors + test issues to the extent that is possible in a separate PR, some of which you've touched upon. To avoid further conflicts this should just merge as is no?

**Comment by fdmalone** [comment]
This is an issue due to the incomplete ROCM libraries (or rather HIP) with a mismatch in what is being released. Either I move entirely to rocm libraries (give up on the portability of hip for the time being) or we just live with the mess for a few more releases? I'm fine with either.

**Comment by ye-luo** [comment]
> This is an issue due to the incomplete ROCM libraries (or rather HIP) with a mismatch in what is being released. Either I move entirely to rocm libraries (give up on the portability of hip for the time being) or we just live with the mess for a few more releases? I'm fine with either.

I didn't mean you cannot mix hip and rocm libraries. If you have #include<hip.h> for the runtime API
and #inlcude<robsolver> for the library. Then I any cpp dependends on them needs to be linked with both libraries. It is better to avoid. For the moment, you can keep developing without getting bothered by this.

**Comment by fdmalone** [comment]
I should say, this was largely a copy paste from the CUDA code. Is there a good way to detect unnecessary includes?

**Comment by ye-luo** [comment]
> I should say, this was largely a copy paste from the CUDA code. Is there a good way to detect unnecessary includes?

To my knowledge, unfortunately no. Yes, the CUDA code already has header inclusion problem.

**Comment by PDoakORNL** [comment]
https://include-what-you-use.org/

**Comment by fdmalone** [comment]
I'll give it a go. A clang format of the AFQMC source is also overdue.

**Comment by ye-luo** [comment]
> @ye-luo initially this PR was meant to touch only the CMake source. I will fix the remaining compilation errors + test issues to the extent that is possible in a separate PR, some of which you've touched upon. To avoid further conflicts this should just merge as is no?

I'm a bit confused. Are you asking "To avoid further conflicts this should just merge as is? no?"
I'd like to merge as it is now once the CI pass.

**Comment by prckent** [comment]
@fdmalone Cleaning up includes would be a healthy thing to do. Old QMCPACK code has generally includes too many files.
