### PR TITLE
Fix Debug build failure caused by #3689

### LINKED ISSUE #3690: is_spinor_ is a private member in an assert statement
**Describe the bug**

```
/builds/correaa/boost-mpi3/qmcpack/src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp: In member function 'virtual qmcplusplus::WaveFunctionComponent::LogValueType qmcplusplus::MultiDiracDeterminant::updateBuffer(qmcplusplus::ParticleSet&, qmcplusplus::WaveFunctionComponent::WFBufferType&, bool)':
/builds/correaa/boost-mpi3/qmcpack/src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp:270:12: error: 'bool qmcplusplus::ParticleSet::is_spinor_' is protected within this context
  270 |   assert(P.is_spinor_ == is_spinor_);
```

**To Reproduce**

compile with DEBUG flags.

Is the github CI compiling in debug mode at all?

**Expected behavior**

should compile. Be public for example.

**System:**

Debian testing

**Additional context**

https://gitlab.com/correaa/boost-mpi3/-/jobs/1924471860#L1734

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Closes #3690 

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
